#' @title DC.CO_plot
#'
#' @description Plot the differential cooccurrence data
#'
#' @param obj Object generated by Stat.Extraction function. Required
#' @param col_negOR Color palette to color mutual exclusion paires from stong to weak. Optional. Default: c("blue","light blue")
#' @param col_zero Color palette to color paires with no/very week cooccurrence/mutual exclusion. Optional. Default: c("white")
#' @param col_posOR Color palette to color cooccurrency paires from weak to strong. Optional. Default: c("pink","red")
#' @param plot.oma Oma parameter of par function (to manually adjust plot). Optional. Default: NULL(automatically adjust)
#' @param plot.mar Mar parameter of par function (to manually adjust plot). Optional. Default: NULL(automatically adjust)
#' @param xlim_leftAdj Numerical. Set the x-axis lower limits. Optional. Default: NULL(automatically adjust)
#' @param xlim_rightAdj Numerical. Set the x-axis upper limits. Optional. Default: NULL(automatically adjust)
#' @param ylim_lowerAdj Numerical. Set the y-axis lower limits. Optional. Default: NULL(automatically adjust)
#' @param ylim_upperAdj Numerical. Set the y-axis upper limits. Optional. Default: NULL(automatically adjust)
#' @param grid.color Grid color. Optional. Default: "grey50"
#' @param grid.lwd Numerical. Grid line width. Optional. Default: 0.7
#' @param sig_CO.symbol Symbol to label the significance in cooccurrence pairs. Optional. Default: "*"
#' @param sig_CO.cex Numerical. Size of "sig_CO.symbol". Optional. Default: 2
#' @param sig_CO.col Color of "sig_CO.symbol". Optional. Default: "black"
#' @param sig_DE.col Grid color to denote there is significant differential occurrence. Applys to DC mode. Optional. Default: "green".
#' @param sig_DE.lwd Numerical. Line width of grid of significant differential occurrence. Applys to DC mode. Optional. Default: 2
#' @param triangle.lwd Numerical. Line width of the triangle. Applys to DC or Separate mode. Optional. Default: 1
#' @param label.gene.offset.vertical Numerical. Offset to label the gene name against the upper side of the grid. Optional. Default: 0.7
#' @param label.gene.offset.horiz Numerical. Offset to label the gene name against the left side of the grid. Optional. Default: 0.5
#' @param label.gene.col Color to label the gene name. Optional. Default: "black"
#' @param label.gene.font Font to lable the gene name. Optional. Default: 3
#' @param label.gene.cex Size of the gene name. Optional. Default: 1
#' @param legend.offset.X Numerical. Offset between the color legend and the right side of gird. Optional. Default: 1
#' @param legend.y.below.manualset Numerical. Manually set up the lower y position of the color legend. Optional. Default: NULL(automatically adjust)
#' @param legend.y.height.manualset Numerical. Manually set up the height of the color legend. Optional.Default: NULL(automatically adjust)
#' @param legend.width Numerical. The width of the color legend. Optional. Default: Default: 0.5
#' @param text.logor.offset Numerical. Offset of "LogOR" against the upper side of color legend. Optional.Default: NULL(automatically adjust)
#' @param legend.text.cex Numerical. Size of the text in legend. Optional. Default: 1
#' @param legend.text.length Numerical. Sequence length of the range of LogOR to label in color length. Optional. Default: 5
#' @param legend.triangle.position Position to place the legend of triangle, significance and FDR. Two options: "Right" or "LeftBottom". Optional.Default: NULL(automatically adjust)
#'
#'
#'
#' @return The plot
#' @export
#' @examples
#' data(gbm_dat)
#' cohort<-gbm_dat$cohort;unique(cohort)
#' dat<-gbm_dat[,-1]
#'
#' Result_Separate<-DC.CO_Evaluation(mutation_data=dat,
#'                                   group=cohort,
#'                                   which_group_to_be_one="UT",
#'                                   mode="Separate",
#'                                   adjust.method="BH",
#'                                   FDRCutoff=0.05)
#' Sig_Separate<-Stat.Extraction(obj=Result_Separate,WhichGrp_adjP.Separate="Each")
#' DC.CO_plot(obj=Sig_Separate)


###################################
DC.CO_plot<-function(obj=obj,
                     col_negOR=c("blue","light blue"),
                     col_zero="white",
                     col_posOR=c("pink", "red"),
                     plot.oma=NULL,
                     plot.mar=NULL,
                     xlim_leftAdj=NULL,
                     xlim_rightAdj=NULL,
                     ylim_lowerAdj=NULL,
                     ylim_upperAdj=NULL,
                     grid.color="grey50",
                     grid.lwd=0.7,
                     sig_CO.symbol="*",
                     sig_CO.cex=2,
                     sig_CO.col="black",
                     sig_DE.col="green",
                     sig_DE.lwd=2,
                     triangle.lwd=1,
                     label.gene.offset.vertical=0.7,
                     label.gene.offset.horiz=0.5,
                     label.gene.col="black",
                     label.gene.font=3,
                     label.gene.cex=1,
                     legend.offset.X=1,
                     legend.y.below.manualset=NULL,
                     legend.y.height.manualset=NULL,
                     legend.width=0.5,
                     text.logor.offset=NULL,  ###y offset of "LogOR"
                     legend.text.cex=1,
                     legend.text.length=5, #legend.text.length=7, laboffset=0.2, tl.col="black",tl.cex=1,txt.offset=0.2
                     legend.triangle.position=NULL#, ##"Right",#NULL, LeftBottom
                     ){
 # library(plotrix)
  sig_CO.FDRCutoff=NULL ### Decide not to use this as one of parameter in the function
  resultObj<-obj
  WhichGrp_adjP.Separate<-resultObj$WhichGrp_adjP.Separate

  obj=resultObj$obj
  FDRCutoff=obj$FDRCutoff
  DE_mode<-obj$mode
  if(!DE_mode=="Single"){
    group=obj$group
    which_group_to_be_one=obj$which_group_to_be_one
    uniGroup<-unique(group)
  }


  obj_coord<-make_Coord_df(obj=obj,
                           DE_mode=DE_mode,
                           FDRCutoff=FDRCutoff,
                           col_negOR=col_negOR,
                           col_zero=col_zero,
                           col_posOR=col_posOR)

  if(DE_mode=="DC"){
    rang_X<-range(obj_coord$CoordList$OR_CO$X); rang_Y<-range(obj_coord$CoordList$OR_CO$Y)
    coordIn_main<-obj_coord$CoordList$OR_CO
    coordIn_FDRmain<-obj_coord$CoordList$FDR_CO
    sig_CO.FDRCutoff<-ifelse(is.null(sig_CO.FDRCutoff),FDRCutoff,sig_CO.FDRCutoff)
    coordIn_FDRmain_sig<-coordIn_FDRmain[coordIn_FDRmain$FDR_CO<sig_CO.FDRCutoff,]

    coordIn_OR_grp0<-obj_coord$CoordList$OR_grp0;coordIn_OR_grp0<-coordIn_OR_grp0[!is.na(coordIn_OR_grp0$ScaledOR),]
    coordIn_OR_grp1<-obj_coord$CoordList$OR_grp1;coordIn_OR_grp1<-coordIn_OR_grp1[!is.na(coordIn_OR_grp1$ScaledOR),]
    original_Matrix<-obj_coord$matrix_obj$OR_CO
  }

  if(DE_mode=="Separate"){
    plotDat_withSigAdded<-check_Sig_SepGrp(dataIn=obj_coord$CoordList,
                                           WhichGrp_adjP.Separate=WhichGrp_adjP.Separate,
                                           FDRCutoff=FDRCutoff,
                                           which_group_to_be_one=which_group_to_be_one,
                                           uniGroup=uniGroup)
    plotDat_grp0<-plotDat_withSigAdded$P_OR_group0; plotDat_grp1<-plotDat_withSigAdded$P_OR_group1

    rang_X<-range(plotDat_grp0$X); rang_Y<-range(plotDat_grp0$Y)
    coordIn_main<-plotDat_grp0
    coordIn_FDRmain<-obj_coord$matrix_obj$FDRCutoff

    coordIn_OR_grp0<-plotDat_grp0;coordIn_OR_grp0<-coordIn_OR_grp0[!is.na(coordIn_OR_grp0$OR_scaled),]
    coordIn_OR_grp1<-plotDat_grp1;coordIn_OR_grp1<-coordIn_OR_grp1[!is.na(coordIn_OR_grp1$OR_scaled),]

    original_Matrix<-obj_coord$matrix_obj$P_OR_group0$ElogOR
    sig_CO.FDRCutoff=FDRCutoff  #for XYlim_set
  }

  if(DE_mode=="Single"){
    plotDat<-obj_coord$CoordList$Single
    rang_X<-range(plotDat$X); rang_Y<-range(plotDat$Y)
    coordIn_main<-plotDat
    coordIn_FDRmain<-obj_coord$matrix_obj$FDRCutoff

    coordIn_OR_grp0<-plotDat

    original_Matrix<-obj_coord$matrix_obj$ElogOR
    sig_CO.FDRCutoff=FDRCutoff;uniGroup="Test"  #for XYlim_set
  }
  #########################################################################################################
  plot.new()
  if(!is.null(plot.oma)){par(oma=plot.oma)}
  if(!is.null(plot.mar)){par(mar=plot.mar)}
  plot_xlab<-colnames(original_Matrix);plot_ylab<-row.names(original_Matrix)
  max_length_geneName<-max(strwidth(c(plot_xlab,plot_ylab),cex=label.gene.cex,units="inches")) ##max length of gene label name

  XYlim_set<-xylim(rang_X=rang_X,
                   rang_Y=rang_Y,
                   sig_CO.FDRCutoff=sig_CO.FDRCutoff,
                   max_length_geneName=max_length_geneName,
                   label.gene.offset.vertical=label.gene.offset.vertical,
                   label.gene.offset.horiz=label.gene.offset.horiz,
                   uniGroup=uniGroup,
                   label.gene.cex=label.gene.cex,
                   legend.offset.X=legend.offset.X,
                   legend.width=legend.width,
                   legend.text.cex=legend.text.cex)
  X_left<-ifelse(is.null(xlim_leftAdj),XYlim_set$xlim_left,rang_X[1]-xlim_leftAdj)
  X_right<-ifelse(is.null(xlim_rightAdj),XYlim_set$xlim_right,rang_X[2]+xlim_rightAdj)
  Y_left<-ifelse(is.null(ylim_lowerAdj),XYlim_set$ylim_left,rang_Y[1]-ylim_lowerAdj)
  Y_right<-ifelse(is.null(ylim_upperAdj),XYlim_set$ylim_right,rang_Y[2]+ylim_upperAdj)

  plot.window(xlim = c(X_left,X_right),ylim = c(Y_left,Y_right), asp = 1, xlab = "", ylab = "", xaxs = "i", yaxs = "i")
  ##generate grid###
  symbols(coordIn_main[,1:2], add = TRUE, inches = FALSE,rectangles = matrix(1, nrow = nrow(coordIn_main), ncol = 2),bg=NA , fg=grid.color,lwd=grid.lwd)
  #########################################################################################################
  ###add symbols
  add_symbols(DE_mode=DE_mode,
              coordIn_main=coordIn_main,
              coordIn_FDRmain_sig=coordIn_FDRmain_sig,
              sig_CO.symbol=sig_CO.symbol,
              sig_CO.cex=sig_CO.cex,
              sig_CO.col=sig_CO.col,
              coordIn_OR_grp0=coordIn_OR_grp0,
              coordIn_OR_grp1=coordIn_OR_grp1,
              sig_DE.col=sig_DE.col,
              sig_DE.lwd=sig_DE.lwd,
              triangle.lwd=triangle.lwd,
              grid.color=grid.color,
              grid.lwd=grid.lwd,
              FDRCutoff=FDRCutoff)

  ####add gene names
  add_geneName(coordIn_main=coordIn_main,
               label.gene.offset.vertical=label.gene.offset.vertical,
               label.gene.offset.horiz=label.gene.offset.horiz,
               plot_xlab=plot_xlab,
               plot_ylab=plot_ylab,
               label.gene.col=label.gene.col,
               label.gene.font=label.gene.font,
               label.gene.cex=label.gene.cex)


  ####add legend##
  legend.y.returned<-add_legend(coordIn_main=coordIn_main,
                                legend.offset.X=legend.offset.X,
                                legend.triangle.position=legend.triangle.position,
                                legend.y.below.manualset=legend.y.below.manualset,
                                legend.y.height.manualset=legend.y.height.manualset,
                                obj_coord=obj_coord,
                                legend.width=legend.width,
                                legend.Height=legend.Height,
                                text.logor.offset=text.logor.offset,
                                legend.text.cex=legend.text.cex,
                                legend.text.length=legend.text.length)


  ####upper/lower trangel and FDR##
  if(is.null(legend.triangle.position)){
    legend.triangle.position<-ifelse(length(unique(coordIn_main[,2]))>10,"Right","LeftBottom")}

  if(legend.triangle.position=="LeftBottom"){ #####LeftBottom  legend
    add_triangle_FDR_LeftBottom(coordIn_main=coordIn_main,
                                DE_mode=DE_mode,
                                coordIn_OR_grp0=coordIn_OR_grp0,
                                coordIn_OR_grp1=coordIn_OR_grp1,
                                triangle.lwd=triangle.lwd,
                                label.gene.offset.horiz=label.gene.offset.horiz,
                                uniGroup=uniGroup,
                                which_group_to_be_one=which_group_to_be_one,
                                FDRCutoff=FDRCutoff,
                                sig_DE.col=sig_DE.col,
                                sig_DE.lwd=sig_DE.lwd,
                                sig_CO.FDRCutoff=sig_CO.FDRCutoff,
                                sig_CO.symbol=sig_CO.symbol,
                                sig_CO.cex=sig_CO.cex,
                                sig_CO.col=sig_CO.col,
                                label.gene.cex=label.gene.cex,
                                legend.text.cex=legend.text.cex,
                                coordIn_FDRmain_sig=coordIn_FDRmain_sig)}


  if(legend.triangle.position=="Right"){ ##right  legend
    add_triangle_FDR_Right(legend.y=legend.y.returned,
                           coordIn_main=coordIn_main,
                           DE_mode=DE_mode,
                           triangle.lwd=triangle.lwd,
                           label.gene.offset.horiz=label.gene.offset.horiz,
                           uniGroup=uniGroup,
                           which_group_to_be_one=which_group_to_be_one,
                           legend.text.cex=legend.text.cex,
                           legend.offset.X=legend.offset.X,
                           legend.y.below.manualset=legend.y.below.manualset,
                           sig_DE.col=sig_DE.col,
                           sig_DE.lwd=sig_DE.lwd,
                           sig_CO.FDRCutoff=sig_CO.FDRCutoff,
                           label.gene.cex=label.gene.cex,
                           coordIn_OR_grp0=coordIn_OR_grp0,
                           coordIn_OR_grp1=coordIn_OR_grp1,
                           FDRCutoff=FDRCutoff,
                           sig_CO.symbol=sig_CO.symbol,
                           sig_CO.cex=sig_CO.cex,
                           sig_CO.col=sig_CO.col,
                           coordIn_FDRmain_sig=coordIn_FDRmain_sig)}
}


