#' @title Stat.Extraction
#'
#' @description Extract the statistics from the object generated by DC.CO_Evaluation
#'
#' @param obj Object generated by DC.CO_Evaluation function. Required
#' @param WhichGrp_adjP.Separate Which group to adjust p value in separate mode. Restricts to separate mode only. Option includes: NULL(p value adjusted by entire dataset), "All"(p value adjusted by entire dataset), "None"(no p value adjustment), "Each"(p value adjusted within each group). The value can also be one of the category of the group parameter. In this case, p value within the specified group is adjusted while the other group shows the raw p value. Optional. Default: NULL
#'
#'
#'
#' @return A data frame with log odds ratio, raw p value, fasle discovery rate and significance
#' @export
#' @examples
#' data(gbm_dat)
#' cohort<-gbm_dat$cohort;unique(cohort)
#' dat<-gbm_dat[,-1]
#'
#' Result_Separate<-DC.CO_Evaluation(mutation_data=dat,
#'                                   group=cohort,
#'                                   which_group_to_be_one="UT",
#'                                   mode="Separate",
#'                                   adjust.method="BH",
#'                                   FDRCutoff=0.05)
#' Sig_Separate<-Stat.Extraction(obj=Result_Separate)




Stat.Extraction<-function(obj=obj_input,WhichGrp_adjP.Separate=NULL){
  testmode<-obj$mode
  if(testmode=="DC"){
    output<-extract_stat_DC(obj=obj)
  }
  if(testmode=="Separate"){
    output<-extract_stat_Sep(obj=obj,WhichGrp_adjP.Separate=WhichGrp_adjP.Separate)
  }
  if(testmode=="Single"){
    output<-extract_stat_single(obj=obj)
  }
  out<-list(Stat=output,obj=obj,WhichGrp_adjP.Separate=WhichGrp_adjP.Separate)
  return(out)
}
